# Generated by Django 4.1.3 on 2022-12-03 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headings',
            name='btnCode',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='headings',
            name='subHeading',
            field=models.CharField(max_length=500),
        ),
    ]
